server:
  port: 10029

spring:
  application:
    name: common-util
  data:
    mongodb:
      uri: mongodb://192.168.110.29:27017/THZ

some:
  value: yml文件值自动注入

complex:
  value-list:
    - 123
    - 456
    - 789

